name: Release Tags

on: push

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn
      - run: VERSION=$(node -e "console.log(require('./lerna.json').version)") yarn build
      - run: VERSION=$(node -e "console.log(require('./lerna.json').version)") NODE_OPTIONS="--max_old_space_size=6144" DEFAULT_NETWORK_ID="137" HIDE_FAUCET="true" yarn simp build
      - run: VERSION=$(node -e "console.log(require('./lerna.json').version)") NODE_OPTIONS="--max_old_space_size=6144" DEFAULT_NETWORK_ID="137" HIDE_FAUCET="true" yarn sport build
      - run: yarn smart generate:environments
      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v6.2
        id: verify-changed-files
        with:
         files: |
          packages/smart/environments/matic.json
          packages/smart/addresses.ts
      - name: Redeploy the subgraph when the environment changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          yarn subgraph prepare:abis
          yarn subgraph prepare:matic
          yarn subgraph codegen
          yarn subgraph deploy:matic --access-token ${{ secrets.GRAPH_TOKEN }}
      - name: Compress action step
        uses: master-atul/tar-action@v1.0.2
        id: compress-turbo
        with:
          command: c
          cwd: ./packages/simplified/
          files: |
            ./build
          outPath: turbo.tar.gz
      - name: Compress sporsbook action step
        uses: master-atul/tar-action@v1.0.2
        id: compress-sport
        with:
          command: c
          cwd: ./packages/sport/
          files: |
            ./build
          outPath: sport.tar.gz
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            LICENSE
            sport.tar.gz
            turbo.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
